import "@/styles/globals.css";

import localFont from "next/font/local";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";

const pano = localFont({
  src: [
    {
      path: "../styles/fonts/HW Pano Regular.woff",
      weight: "500",
    },
    {
      path: "../styles/fonts/HW Pano Bold.woff",
      weight: "700",
    },
  ],
  display: "swap",
  variable: "--font-pano",
});

export const metadata = {
  title: "EasterCup",
  // description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${pano.variable}`}>
      <body className="font-pano">
        <TRPCReactProvider cookies={cookies().toString()}>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
